[package]
name = "simulated_annealing"
version = "0.1.0"
edition = "2021"
[dependencies]
ordered-float = { version = "3.0", default-features = false }
sqlite = "0.30.4"
libm = "0.2.6"
rand = "0.8.5"
rand_distr = "0.4.3"
[profile.release]
panic = 'abort'
